// src/components/clients/client-form.tsx
'use client'

import { useState, useEffect, useMemo, useCallback } from 'react'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { toast } from 'sonner'
import { useRouter } from 'next/navigation'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog'
import { Client, CreateClientRequest, Address, EmergencyContact, Lifestyle, BaselineVitals } from '@/types/api'
import { X, Plus, Check, ChevronRight, ChevronLeft, Edit } from 'lucide-react'
import { ClientMedications } from './client-medications'
import { ClientImmunizations } from './client-immunizations'
import { ClientTestResults } from './client-test-results'

type Props = {
  initialData?: Partial<Client>
  onSubmit: (data: CreateClientRequest) => void | Promise<void>
  isLoading?: boolean
}

type FormData = {
  refNumber?: string
  firstName: string
  fatherName: string
  lastName: string
  fullName: string
  phone: string
  gender: '' | 'male' | 'female'
  dateOfBirth: string
  nationalId: string
  idNumber: string
  passportNumber: string
  maritalStatus: '' | 'single' | 'married' | 'divorced' | 'widowed'
  nationality: string
  email: string
  address: Address
  emergencyContact: EmergencyContact
  primaryReasonForVisit: string
  currentMedicalHistory: string
  allergies: string[]
  chronicDiseases: string[]
  previousSurgeries: string[]
  currentMedications: string[]
  familyHistory: string
  dateFileOpening: string
  lifestyle: Lifestyle
  bmi: string
  baselineVitals: BaselineVitals
  appointmentAdherence: string
  improvementNotes: string
  clientClassification: '' | 'regular' | 'new' | 'chronic' | 'VIP'
  medicalHistory?: string
}

const TOTAL_STEPS = 7
const STEP_LABELS = [
  'المعلومات الأساسية',
  'التعريف',
  'العنوان والاتصال',
  'التاريخ الطبي',
  'السجلات',
  'القياسات',
  'التصنيف',
]

export function ClientForm({
  initialData,
  onSubmit = () => {},
  isLoading,
}: Props) {
  const router = useRouter()
  const isEditing = !!initialData
  const [confirmOpen, setConfirmOpen] = useState(false)
  const [currentStep, setCurrentStep] = useState(1)
  const [completedSteps, setCompletedSteps] = useState<number[]>([])
  const [stepErrors, setStepErrors] = useState<{ [key: number]: string }>({})
  const [isSubmitting, setIsSubmitting] = useState(false)

  // Initialize form data
  const [formData, setFormData] = useState<FormData>({
    refNumber: '',
    firstName: '',
    fatherName: '',
    lastName: '',
    fullName: '',
    phone: '',
    gender: 'female',
    dateOfBirth: '',
    nationalId: '',
    idNumber: '',
    passportNumber: '',
    maritalStatus: '',
    nationality: 'سوري',
    email: '',
    address: { city: '', region: '', street: '' },
    emergencyContact: { name: '', phone: '', relationship: '' },
    primaryReasonForVisit: '',
    currentMedicalHistory: '',
    allergies: [],
    chronicDiseases: [],
    previousSurgeries: [],
    currentMedications: [],
    familyHistory: '',
    dateFileOpening: '',
    lifestyle: { smoking: '', alcohol: '', physicalActivity: '', diet: '' },
    bmi: '',
    baselineVitals: { bloodPressure: '', bloodSugar: '', weight: undefined, height: undefined },
    appointmentAdherence: '',
    improvementNotes: '',
    clientClassification: 'new',
    medicalHistory: '',
  })

  // Auto-generate fullName from name components
  const autoGeneratedFullName = useMemo(() => {
    const parts = [formData.firstName, formData.fatherName, formData.lastName].filter(Boolean)
    return parts.join(' ').trim()
  }, [formData.firstName, formData.fatherName, formData.lastName])

  // Initialize from initialData
  useEffect(() => {
    if (initialData) {
      let address: Address = { city: '', region: '', street: '' }
      if (initialData.address) {
        if (typeof initialData.address === 'string') {
          address = { street: initialData.address }
        } else {
          address = initialData.address
        }
      }

      setFormData((prev) => ({
        ...prev,
        refNumber: initialData.refNumber || '',
        firstName: initialData.firstName || '',
        fatherName: initialData.fatherName || '',
        lastName: initialData.lastName || '',
        fullName: initialData.fullName || '',
        phone: initialData.phone || '',
        gender: (initialData.gender === 'male' || initialData.gender === 'female' ? initialData.gender : 'female') as '' | 'male' | 'female',
        dateOfBirth: initialData.dateOfBirth
          ? new Date(initialData.dateOfBirth).toISOString().split('T')[0]
          : '',
        nationalId: initialData.nationalId || '',
        idNumber: initialData.idNumber || '',
        passportNumber: initialData.passportNumber || '',
        maritalStatus: (initialData.maritalStatus as '' | 'single' | 'married' | 'divorced' | 'widowed') || '',
        nationality: initialData.nationality || 'سوري',
        email: initialData.email || '',
        address,
        emergencyContact: initialData.emergencyContact || { name: '', phone: '', relationship: '' },
        primaryReasonForVisit: initialData.primaryReasonForVisit || '',
        currentMedicalHistory: initialData.currentMedicalHistory || '',
        allergies: initialData.allergies || [],
        chronicDiseases: initialData.chronicDiseases || [],
        previousSurgeries: initialData.previousSurgeries || [],
        currentMedications: initialData.currentMedications || [],
        familyHistory: initialData.familyHistory || '',
        dateFileOpening: initialData.dateFileOpening
          ? new Date(initialData.dateFileOpening).toISOString().split('T')[0]
          : '',
        lifestyle: initialData.lifestyle || { smoking: '', alcohol: '', physicalActivity: '', diet: '' },
        bmi: initialData.bmi?.toString() || '',
        baselineVitals: initialData.baselineVitals || {
          bloodPressure: '',
          bloodSugar: '',
          weight: undefined,
          height: undefined,
        },
        appointmentAdherence: initialData.appointmentAdherence || '',
        improvementNotes: initialData.improvementNotes || '',
        clientClassification: (initialData.clientClassification as '' | 'regular' | 'new' | 'chronic' | 'VIP') || 'new',
        medicalHistory: initialData.medicalHistory || '',
      }))
    }
  }, [initialData])

  // Helper functions for array fields
  const addArrayItem = useCallback((field: 'allergies' | 'chronicDiseases' | 'previousSurgeries' | 'currentMedications') => {
    setFormData((prev) => ({
      ...prev,
      [field]: [...prev[field], ''],
    }))
  }, [])

  const updateArrayItem = useCallback((
    field: 'allergies' | 'chronicDiseases' | 'previousSurgeries' | 'currentMedications',
    index: number,
    value: string
  ) => {
    setFormData((prev) => ({
      ...prev,
      [field]: prev[field].map((item, i) => (i === index ? value : item)),
    }))
  }, [])

  const removeArrayItem = useCallback((
    field: 'allergies' | 'chronicDiseases' | 'previousSurgeries' | 'currentMedications',
    index: number
  ) => {
    setFormData((prev) => ({
      ...prev,
      [field]: prev[field].filter((_, i) => i !== index),
    }))
  }, [])

  // Step validation functions
  const validateStep = (step: number): { isValid: boolean; error?: string } => {
    switch (step) {
      case 1:
        if (!formData.firstName || !formData.fatherName || !formData.lastName || !formData.phone || !formData.gender) {
          return { isValid: false, error: 'يرجى تعبئة جميع الحقول الإلزامية (الاسم الأول، اسم الأب، اسم العائلة، رقم الهاتف، الجنس)' }
        }
        return { isValid: true }
      case 2:
      case 3:
      case 4:
      case 5:
      case 6:
      case 7:
        return { isValid: true } // Optional steps
      default:
        return { isValid: true }
    }
  }

  // Navigation functions
  const handleNext = () => {
    const validation = validateStep(currentStep)
    if (!validation.isValid) {
      setStepErrors({ ...stepErrors, [currentStep]: validation.error || '' })
      toast.error(validation.error || 'يرجى إكمال الحقول المطلوبة')
      return
    }

    // Clear error for this step
    const newErrors = { ...stepErrors }
    delete newErrors[currentStep]
    setStepErrors(newErrors)

    // Mark step as completed
    if (!completedSteps.includes(currentStep)) {
      setCompletedSteps([...completedSteps, currentStep])
    }

    // Move to next step
    if (currentStep < TOTAL_STEPS) {
      setCurrentStep(currentStep + 1)
    }
  }

  const handlePrevious = () => {
    if (currentStep > 1) {
      setCurrentStep(currentStep - 1)
    }
  }

  const goToStep = useCallback((step: number) => {
    // Only allow going to completed steps or next step
    if (step <= currentStep || completedSteps.includes(step - 1)) {
      setCurrentStep(step)
    }
  }, [currentStep, completedSteps])

  const handleConfirm = async (e?: React.MouseEvent<HTMLButtonElement>) => {
    // Prevent any form submission
    if (e) {
      e.preventDefault()
      e.stopPropagation()
    }

    // Prevent double submission
    if (isSubmitting) {
      return
    }

    if (formData.gender !== 'male' && formData.gender !== 'female') {
      toast.error('يرجى اختيار الجنس')
      return
    }

    setIsSubmitting(true)

    // Calculate BMI if weight and height are provided
    let calculatedBmi: number | undefined
    if (formData.baselineVitals.weight && formData.baselineVitals.height) {
      const heightInMeters = formData.baselineVitals.height / 100
      calculatedBmi = formData.baselineVitals.weight / (heightInMeters * heightInMeters)
    }

    const payload: CreateClientRequest = {
      refNumber: formData.refNumber || undefined,
      firstName: formData.firstName,
      fatherName: formData.fatherName,
      lastName: formData.lastName,
      fullName: autoGeneratedFullName || formData.fullName,
      phone: formData.phone,
      gender: formData.gender as 'male' | 'female',
      dateOfBirth: formData.dateOfBirth || undefined,
      nationalId: formData.nationalId || undefined,
      idNumber: formData.idNumber || undefined,
      passportNumber: formData.passportNumber || undefined,
      maritalStatus: formData.maritalStatus ? formData.maritalStatus as 'single' | 'married' | 'divorced' | 'widowed' : undefined,
      nationality: formData.nationality || undefined,
      email: formData.email || undefined,
      address: formData.address,
      emergencyContact: formData.emergencyContact,
      primaryReasonForVisit: formData.primaryReasonForVisit || undefined,
      currentMedicalHistory: formData.currentMedicalHistory || undefined,
      allergies: formData.allergies.filter((item) => item.trim() !== ''),
      chronicDiseases: formData.chronicDiseases.filter((item) => item.trim() !== ''),
      previousSurgeries: formData.previousSurgeries.filter((item) => item.trim() !== ''),
      currentMedications: formData.currentMedications.filter((item) => item.trim() !== ''),
      familyHistory: formData.familyHistory || undefined,
      dateFileOpening: formData.dateFileOpening || undefined,
      lifestyle: formData.lifestyle,
      bmi: calculatedBmi || (formData.bmi ? parseFloat(formData.bmi) : undefined),
      baselineVitals: formData.baselineVitals,
      appointmentAdherence: formData.appointmentAdherence || undefined,
      improvementNotes: formData.improvementNotes || undefined,
      clientClassification: formData.clientClassification ? formData.clientClassification as 'regular' | 'new' | 'chronic' | 'VIP' : undefined,
      medicalHistory: formData.medicalHistory || undefined,
    }

    try {
      const result = onSubmit(payload)
      // If onSubmit returns a promise, await it
      if (result && typeof result === 'object' && 'then' in result && typeof result.then === 'function') {
        await result
      }
      // Toast is shown by the parent component, so we don't show it here
      setConfirmOpen(false)
      if (!isEditing) {
        router.push('/clients')
      }
    } catch (error) {
      // Error handling is done by parent
      console.error('Error submitting client form:', error)
    } finally {
      setIsSubmitting(false)
    }
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()

    // If not on last step, go to next step (this handles Enter key press on non-final steps)
    if (currentStep < TOTAL_STEPS) {
      handleNext()
      return
    }

    // Only show confirmation if we're on the last step AND the form was explicitly submitted
    // (not from Enter key press in an input field)
    // Validate final step
    const validation = validateStep(currentStep)
    if (!validation.isValid) {
      toast.error(validation.error || 'يرجى إكمال الحقول المطلوبة')
      return
    }

    // On last step, show confirmation dialog only when Save button is clicked
    setConfirmOpen(true)
  }

  // Separate handler for Save button click to ensure it only triggers on explicit click
  const handleSaveClick = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault()
    e.stopPropagation()

    // Validate final step
    const validation = validateStep(currentStep)
    if (!validation.isValid) {
      toast.error(validation.error || 'يرجى إكمال الحقول المطلوبة')
      return
    }

    // Show confirmation dialog
    setConfirmOpen(true)
  }

  // Progress Indicator Component
  const ProgressIndicator = () => {
    return (
      <div className='mb-6' dir='rtl'>
        <div className='flex items-center justify-between mb-2'>
          <h3 className='text-sm font-medium text-gray-700'>
            الخطوة {currentStep} من {TOTAL_STEPS}
          </h3>
          <div className='text-sm text-gray-500'>{STEP_LABELS[currentStep - 1]}</div>
        </div>
        <div className='flex items-center gap-2'>
          {Array.from({ length: TOTAL_STEPS }, (_, i) => i + 1).map((step) => {
            const isCompleted = completedSteps.includes(step)
            const isCurrent = currentStep === step
            const isClickable = step <= currentStep || completedSteps.includes(step - 1)

            return (
              <div key={step} className='flex items-center flex-1'>
                <button
                  type='button'
                  onClick={() => isClickable && goToStep(step)}
                  disabled={!isClickable}
                  className={`flex items-center justify-center w-10 h-10 rounded-full border-2 transition-all ${
                    isCurrent
                      ? 'bg-primary text-primary-foreground border-primary'
                      : isCompleted
                        ? 'bg-green-100 text-green-700 border-green-500'
                        : 'bg-gray-100 text-gray-400 border-gray-300'
                  } ${isClickable ? 'cursor-pointer hover:scale-110' : 'cursor-not-allowed'}`}
                >
                  {isCompleted ? <Check className='w-5 h-5' /> : <span>{step}</span>}
                </button>
                {step < TOTAL_STEPS && (
                  <div
                    className={`flex-1 h-1 mx-1 ${
                      isCompleted ? 'bg-green-500' : 'bg-gray-300'
                    }`}
                  />
                )}
              </div>
            )
          })}
        </div>
      </div>
    )
  }

  // Preview Section Component
  const PreviewSection = useMemo(() => {
    const formatAddress = () => {
      if (!formData.address) return '-'
      if (typeof formData.address === 'string') return formData.address
      const parts = [formData.address.city, formData.address.region, formData.address.street].filter(Boolean)
      return parts.join('، ') || '-'
    }

    return (
      <div className='space-y-4'>
          {/* Step 1: Basic Info */}
          <div className='border-b border-gray-200 pb-4'>
            <div className='flex items-center justify-between mb-3'>
              <h4 className='font-semibold text-gray-800'>المعلومات الأساسية</h4>
              <Button type='button' variant='outline' size='sm' onClick={() => goToStep(1)} className='h-7 text-xs'>
                <Edit className='w-3 h-3 mr-1' />
                تعديل
              </Button>
            </div>
            <div className='grid grid-cols-1 gap-2 text-sm'>
              <p className='flex justify-between'><span className='font-medium text-gray-600'>الاسم:</span> <span className='text-gray-900'>{formData.fullName || autoGeneratedFullName || '-'}</span></p>
              <p className='flex justify-between'><span className='font-medium text-gray-600'>رقم الهاتف:</span> <span className='text-gray-900'>{formData.phone || '-'}</span></p>
              <p className='flex justify-between'><span className='font-medium text-gray-600'>الجنس:</span> <span className='text-gray-900'>{formData.gender === 'male' ? 'ذكر' : formData.gender === 'female' ? 'أنثى' : '-'}</span></p>
              <p className='flex justify-between'><span className='font-medium text-gray-600'>تاريخ الميلاد:</span> <span className='text-gray-900'>{formData.dateOfBirth || '-'}</span></p>
            </div>
          </div>

          {/* Step 2: Identification */}
          <div className='border-b border-gray-200 pb-4'>
            <div className='flex items-center justify-between mb-3'>
              <h4 className='font-semibold text-gray-800'>التعريف</h4>
              <Button type='button' variant='outline' size='sm' onClick={() => goToStep(2)} className='h-7 text-xs'>
                <Edit className='w-3 h-3 mr-1' />
                تعديل
              </Button>
            </div>
            <div className='grid grid-cols-1 gap-2 text-sm'>
              <p className='flex justify-between'><span className='font-medium text-gray-600'>رقم الهوية الوطنية:</span> <span className='text-gray-900'>{formData.nationalId || '-'}</span></p>
              <p className='flex justify-between'><span className='font-medium text-gray-600'>رقم الهوية:</span> <span className='text-gray-900'>{formData.idNumber || '-'}</span></p>
              <p className='flex justify-between'><span className='font-medium text-gray-600'>رقم جواز السفر:</span> <span className='text-gray-900'>{formData.passportNumber || '-'}</span></p>
              <p className='flex justify-between'><span className='font-medium text-gray-600'>الحالة الاجتماعية:</span> <span className='text-gray-900'>{
                formData.maritalStatus === 'single' ? 'أعزب' :
                formData.maritalStatus === 'married' ? 'متزوج' :
                formData.maritalStatus === 'divorced' ? 'مطلق' :
                formData.maritalStatus === 'widowed' ? 'أرمل' : '-'
              }</span></p>
              <p className='flex justify-between'><span className='font-medium text-gray-600'>الجنسية:</span> <span className='text-gray-900'>{formData.nationality || '-'}</span></p>
              <p className='flex justify-between'><span className='font-medium text-gray-600'>البريد الإلكتروني:</span> <span className='text-gray-900'>{formData.email || '-'}</span></p>
            </div>
          </div>

          {/* Step 3: Address & Contact */}
          <div className='border-b border-gray-200 pb-4'>
            <div className='flex items-center justify-between mb-3'>
              <h4 className='font-semibold text-gray-800'>العنوان والاتصال</h4>
              <Button type='button' variant='outline' size='sm' onClick={() => goToStep(3)} className='h-7 text-xs'>
                <Edit className='w-3 h-3 mr-1' />
                تعديل
              </Button>
            </div>
            <div className='text-sm space-y-2'>
              <p className='flex justify-between'><span className='font-medium text-gray-600'>العنوان:</span> <span className='text-gray-900 text-left'>{formatAddress()}</span></p>
              <p className='flex justify-between'><span className='font-medium text-gray-600'>جهة الاتصال:</span> <span className='text-gray-900 text-left'>{
                formData.emergencyContact.name || formData.emergencyContact.phone
                  ? `${formData.emergencyContact.name || ''} - ${formData.emergencyContact.phone || ''} (${formData.emergencyContact.relationship || ''})`
                  : '-'
              }</span></p>
            </div>
          </div>

          {/* Step 4: Medical History */}
          <div className='border-b border-gray-200 pb-4'>
            <div className='flex items-center justify-between mb-3'>
              <h4 className='font-semibold text-gray-800'>التاريخ الطبي</h4>
              <Button type='button' variant='outline' size='sm' onClick={() => goToStep(4)} className='h-7 text-xs'>
                <Edit className='w-3 h-3 mr-1' />
                تعديل
              </Button>
            </div>
            <div className='text-sm space-y-2'>
              {formData.primaryReasonForVisit && <p className='flex justify-between'><span className='font-medium text-gray-600'>السبب الرئيسي:</span> <span className='text-gray-900 text-left max-w-[60%]'>{formData.primaryReasonForVisit}</span></p>}
              {formData.currentMedicalHistory && <p className='flex justify-between'><span className='font-medium text-gray-600'>التاريخ الطبي:</span> <span className='text-gray-900 text-left max-w-[60%]'>{formData.currentMedicalHistory}</span></p>}
              {formData.allergies.length > 0 && <p className='flex justify-between'><span className='font-medium text-gray-600'>الحساسيات:</span> <span className='text-gray-900 text-left max-w-[60%]'>{formData.allergies.filter(Boolean).join('، ') || '-'}</span></p>}
              {formData.chronicDiseases.length > 0 && <p className='flex justify-between'><span className='font-medium text-gray-600'>الأمراض المزمنة:</span> <span className='text-gray-900 text-left max-w-[60%]'>{formData.chronicDiseases.filter(Boolean).join('، ') || '-'}</span></p>}
              {formData.familyHistory && <p className='flex justify-between'><span className='font-medium text-gray-600'>التاريخ العائلي:</span> <span className='text-gray-900 text-left max-w-[60%]'>{formData.familyHistory}</span></p>}
            </div>
          </div>

          {/* Step 6: Measurements */}
          <div className='border-b border-gray-200 pb-4'>
            <div className='flex items-center justify-between mb-3'>
              <h4 className='font-semibold text-gray-800'>القياسات</h4>
              <Button type='button' variant='outline' size='sm' onClick={() => goToStep(6)} className='h-7 text-xs'>
                <Edit className='w-3 h-3 mr-1' />
                تعديل
              </Button>
            </div>
            <div className='grid grid-cols-1 gap-2 text-sm'>
              {formData.baselineVitals.bloodPressure && <p className='flex justify-between'><span className='font-medium text-gray-600'>ضغط الدم:</span> <span className='text-gray-900'>{formData.baselineVitals.bloodPressure}</span></p>}
              {formData.baselineVitals.bloodSugar && <p className='flex justify-between'><span className='font-medium text-gray-600'>السكر:</span> <span className='text-gray-900'>{formData.baselineVitals.bloodSugar}</span></p>}
              {formData.baselineVitals.weight && <p className='flex justify-between'><span className='font-medium text-gray-600'>الوزن:</span> <span className='text-gray-900'>{formData.baselineVitals.weight} كجم</span></p>}
              {formData.baselineVitals.height && <p className='flex justify-between'><span className='font-medium text-gray-600'>الطول:</span> <span className='text-gray-900'>{formData.baselineVitals.height} سم</span></p>}
            </div>
          </div>

          {/* Step 7: Classification */}
          <div>
            <div className='flex items-center justify-between mb-3'>
              <h4 className='font-semibold text-gray-800'>التصنيف</h4>
              <Button type='button' variant='outline' size='sm' onClick={() => goToStep(7)} className='h-7 text-xs'>
                <Edit className='w-3 h-3 mr-1' />
                تعديل
              </Button>
            </div>
            <div className='text-sm space-y-2'>
              <p className='flex justify-between'><span className='font-medium text-gray-600'>التصنيف:</span> <span className='text-gray-900'>{
                formData.clientClassification === 'new' ? 'جديد' :
                formData.clientClassification === 'regular' ? 'عادي' :
                formData.clientClassification === 'chronic' ? 'مزمن' :
                formData.clientClassification === 'VIP' ? 'VIP' : '-'
              }</span></p>
              {formData.appointmentAdherence && <p className='flex justify-between'><span className='font-medium text-gray-600'>الالتزام:</span> <span className='text-gray-900 text-left max-w-[60%]'>{formData.appointmentAdherence}</span></p>}
              {formData.improvementNotes && <p className='flex justify-between'><span className='font-medium text-gray-600'>ملاحظات:</span> <span className='text-gray-900 text-left max-w-[60%]'>{formData.improvementNotes}</span></p>}
            </div>
          </div>
      </div>
    )
  }, [formData, autoGeneratedFullName, goToStep])

  // Step Components
  const Step1BasicInfo = useMemo(() => (
    <div className='space-y-4'>
      <h3 className='text-lg font-semibold mb-4'>المعلومات الأساسية</h3>
      {stepErrors[1] && <p className='text-red-500 text-sm'>{stepErrors[1]}</p>}
      <div className='grid grid-cols-1 md:grid-cols-2 gap-4'>
        {isEditing && formData.refNumber && (
          <div>
            <Label htmlFor='refNumber'>رقم الملف</Label>
            <Input id='refNumber' value={formData.refNumber} disabled className='bg-gray-100' />
          </div>
        )}
        <div>
          <Label htmlFor='firstName'>الاسم الأول *</Label>
          <Input
            id='firstName'
            value={formData.firstName}
            onChange={(e) => setFormData((prev) => ({ ...prev, firstName: e.target.value }))}
            required
          />
        </div>
        <div>
          <Label htmlFor='fatherName'>اسم الأب *</Label>
          <Input
            id='fatherName'
            value={formData.fatherName}
            onChange={(e) => setFormData((prev) => ({ ...prev, fatherName: e.target.value }))}
            required
          />
        </div>
        <div>
          <Label htmlFor='lastName'>اسم العائلة *</Label>
          <Input
            id='lastName'
            value={formData.lastName}
            onChange={(e) => setFormData((prev) => ({ ...prev, lastName: e.target.value }))}
            required
          />
        </div>
        <div>
          <Label htmlFor='fullName'>الاسم الكامل</Label>
          <Input
            id='fullName'
            value={autoGeneratedFullName || formData.fullName}
            disabled
            className='bg-gray-100'
          />
        </div>
        <div>
          <Label htmlFor='phone'>رقم الهاتف *</Label>
          <Input
            id='phone'
            value={formData.phone}
            onChange={(e) => setFormData((prev) => ({ ...prev, phone: e.target.value }))}
            required
          />
        </div>
        <div>
          <Label htmlFor='gender'>الجنس *</Label>
          <Select
            key={`gender-${formData.gender}`}
            value={formData.gender || undefined}
            onValueChange={(value) => setFormData((prev) => ({ ...prev, gender: value as 'male' | 'female' }))}
            required
          >
            <SelectTrigger>
              <SelectValue placeholder='اختر الجنس' />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value='male'>ذكر</SelectItem>
              <SelectItem value='female'>أنثى</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div>
          <Label htmlFor='dateOfBirth'>تاريخ الميلاد</Label>
          <Input
            id='dateOfBirth'
            type='date'
            value={formData.dateOfBirth}
            onChange={(e) => setFormData((prev) => ({ ...prev, dateOfBirth: e.target.value }))}
          />
        </div>
      </div>
    </div>
  ), [formData, stepErrors, isEditing, autoGeneratedFullName])

  const Step2Identification = useMemo(() => (
    <div className='space-y-4'>
      <h3 className='text-lg font-semibold mb-4'>التعريف</h3>
      <div className='grid grid-cols-1 md:grid-cols-2 gap-4'>
        <div>
          <Label htmlFor='nationalId'>رقم الهوية الوطنية</Label>
          <Input
            id='nationalId'
            value={formData.nationalId}
            onChange={(e) => setFormData((prev) => ({ ...prev, nationalId: e.target.value }))}
          />
        </div>
        <div>
          <Label htmlFor='idNumber'>رقم الهوية</Label>
          <Input
            id='idNumber'
            value={formData.idNumber}
            onChange={(e) => setFormData((prev) => ({ ...prev, idNumber: e.target.value }))}
          />
        </div>
        <div>
          <Label htmlFor='passportNumber'>رقم جواز السفر</Label>
          <Input
            id='passportNumber'
            value={formData.passportNumber}
            onChange={(e) => setFormData((prev) => ({ ...prev, passportNumber: e.target.value }))}
          />
        </div>
        <div>
          <Label htmlFor='maritalStatus'>الحالة الاجتماعية</Label>
          <Select
            value={formData.maritalStatus}
            onValueChange={(value) =>
              setFormData((prev) => ({
                ...prev,
                maritalStatus: value as 'single' | 'married' | 'divorced' | 'widowed',
              }))
            }
          >
            <SelectTrigger>
              <SelectValue placeholder='اختر الحالة الاجتماعية' />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value='single'>أعزب</SelectItem>
              <SelectItem value='married'>متزوج</SelectItem>
              <SelectItem value='divorced'>مطلق</SelectItem>
              <SelectItem value='widowed'>أرمل</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div>
          <Label htmlFor='nationality'>الجنسية</Label>
          <Input
            id='nationality'
            value={formData.nationality}
            onChange={(e) => setFormData((prev) => ({ ...prev, nationality: e.target.value }))}
          />
        </div>
        <div>
          <Label htmlFor='email'>البريد الإلكتروني</Label>
          <Input
            id='email'
            type='email'
            value={formData.email}
            onChange={(e) => setFormData((prev) => ({ ...prev, email: e.target.value }))}
          />
        </div>
      </div>
    </div>
  ), [formData])

  const Step3AddressContact = useMemo(() => (
    <div className='space-y-4'>
      <h3 className='text-lg font-semibold mb-4'>العنوان والاتصال</h3>
      <div className='space-y-2'>
        <Label>العنوان</Label>
        <div className='grid grid-cols-1 md:grid-cols-3 gap-4'>
          <div>
            <Label htmlFor='addressCity' className='text-sm text-gray-600'>المدينة</Label>
            <Input
              id='addressCity'
              value={formData.address.city || ''}
              onChange={(e) =>
                setFormData((prev) => ({
                  ...prev,
                  address: { ...prev.address, city: e.target.value },
                }))
              }
            />
          </div>
          <div>
            <Label htmlFor='addressRegion' className='text-sm text-gray-600'>المنطقة</Label>
            <Input
              id='addressRegion'
              value={formData.address.region || ''}
              onChange={(e) =>
                setFormData((prev) => ({
                  ...prev,
                  address: { ...prev.address, region: e.target.value },
                }))
              }
            />
          </div>
          <div>
            <Label htmlFor='addressStreet' className='text-sm text-gray-600'>الشارع</Label>
            <Input
              id='addressStreet'
              value={formData.address.street || ''}
              onChange={(e) =>
                setFormData((prev) => ({
                  ...prev,
                  address: { ...prev.address, street: e.target.value },
                }))
              }
            />
          </div>
        </div>
      </div>
      <div className='space-y-2'>
        <Label>جهة الاتصال في حالات الطوارئ</Label>
        <div className='grid grid-cols-1 md:grid-cols-3 gap-4'>
          <div>
            <Label htmlFor='emergencyName' className='text-sm text-gray-600'>الاسم</Label>
            <Input
              id='emergencyName'
              value={formData.emergencyContact.name || ''}
              onChange={(e) =>
                setFormData((prev) => ({
                  ...prev,
                  emergencyContact: { ...prev.emergencyContact, name: e.target.value },
                }))
              }
            />
          </div>
          <div>
            <Label htmlFor='emergencyPhone' className='text-sm text-gray-600'>رقم الهاتف</Label>
            <Input
              id='emergencyPhone'
              value={formData.emergencyContact.phone || ''}
              onChange={(e) =>
                setFormData((prev) => ({
                  ...prev,
                  emergencyContact: { ...prev.emergencyContact, phone: e.target.value },
                }))
              }
            />
          </div>
          <div>
            <Label htmlFor='emergencyRelationship' className='text-sm text-gray-600'>صلة القرابة</Label>
            <Input
              id='emergencyRelationship'
              value={formData.emergencyContact.relationship || ''}
              onChange={(e) =>
                setFormData((prev) => ({
                  ...prev,
                  emergencyContact: { ...prev.emergencyContact, relationship: e.target.value },
                }))
              }
            />
          </div>
        </div>
      </div>
    </div>
  ), [formData])

  const Step4MedicalHistory = useMemo(() => (
    <div className='space-y-4'>
      <h3 className='text-lg font-semibold mb-4'>التاريخ الطبي</h3>
      <div>
        <Label htmlFor='primaryReasonForVisit'>السبب الرئيسي للزيارة</Label>
        <Textarea
          id='primaryReasonForVisit'
          value={formData.primaryReasonForVisit}
          onChange={(e) => setFormData((prev) => ({ ...prev, primaryReasonForVisit: e.target.value }))}
          rows={3}
        />
      </div>
      <div>
        <Label htmlFor='currentMedicalHistory'>التاريخ الطبي الحالي</Label>
        <Textarea
          id='currentMedicalHistory'
          value={formData.currentMedicalHistory}
          onChange={(e) => setFormData((prev) => ({ ...prev, currentMedicalHistory: e.target.value }))}
          rows={4}
        />
      </div>
      <div>
        <div className='flex items-center justify-between mb-2'>
          <Label>الحساسيات</Label>
          <Button type='button' variant='outline' size='sm' onClick={() => addArrayItem('allergies')}>
            <Plus className='w-4 h-4 mr-1' />
            إضافة
          </Button>
        </div>
        <div className='space-y-2'>
          {formData.allergies.map((allergy, index) => (
            <div key={index} className='flex gap-2'>
              <Input
                value={allergy}
                onChange={(e) => updateArrayItem('allergies', index, e.target.value)}
                placeholder='أدخل الحساسية'
              />
              <Button type='button' variant='outline' size='sm' onClick={() => removeArrayItem('allergies', index)}>
                <X className='w-4 h-4' />
              </Button>
            </div>
          ))}
        </div>
      </div>
      <div>
        <div className='flex items-center justify-between mb-2'>
          <Label>الأمراض المزمنة</Label>
          <Button type='button' variant='outline' size='sm' onClick={() => addArrayItem('chronicDiseases')}>
            <Plus className='w-4 h-4 mr-1' />
            إضافة
          </Button>
        </div>
        <div className='space-y-2'>
          {formData.chronicDiseases.map((disease, index) => (
            <div key={index} className='flex gap-2'>
              <Input
                value={disease}
                onChange={(e) => updateArrayItem('chronicDiseases', index, e.target.value)}
                placeholder='أدخل المرض المزمن'
              />
              <Button type='button' variant='outline' size='sm' onClick={() => removeArrayItem('chronicDiseases', index)}>
                <X className='w-4 h-4' />
              </Button>
            </div>
          ))}
        </div>
      </div>
      <div>
        <div className='flex items-center justify-between mb-2'>
          <Label>العمليات الجراحية السابقة</Label>
          <Button type='button' variant='outline' size='sm' onClick={() => addArrayItem('previousSurgeries')}>
            <Plus className='w-4 h-4 mr-1' />
            إضافة
          </Button>
        </div>
        <div className='space-y-2'>
          {formData.previousSurgeries.map((surgery, index) => (
            <div key={index} className='flex gap-2'>
              <Input
                value={surgery}
                onChange={(e) => updateArrayItem('previousSurgeries', index, e.target.value)}
                placeholder='أدخل العملية الجراحية'
              />
              <Button type='button' variant='outline' size='sm' onClick={() => removeArrayItem('previousSurgeries', index)}>
                <X className='w-4 h-4' />
              </Button>
            </div>
          ))}
        </div>
      </div>
      <div>
        <div className='flex items-center justify-between mb-2'>
          <Label>الأدوية الحالية</Label>
          <Button type='button' variant='outline' size='sm' onClick={() => addArrayItem('currentMedications')}>
            <Plus className='w-4 h-4 mr-1' />
            إضافة
          </Button>
        </div>
        <div className='space-y-2'>
          {formData.currentMedications.map((medication, index) => (
            <div key={index} className='flex gap-2'>
              <Input
                value={medication}
                onChange={(e) => updateArrayItem('currentMedications', index, e.target.value)}
                placeholder='أدخل الدواء'
              />
              <Button type='button' variant='outline' size='sm' onClick={() => removeArrayItem('currentMedications', index)}>
                <X className='w-4 h-4' />
              </Button>
            </div>
          ))}
        </div>
      </div>
      <div>
        <Label htmlFor='familyHistory'>التاريخ العائلي للأمراض الوراثية</Label>
        <Textarea
          id='familyHistory'
          value={formData.familyHistory}
          onChange={(e) => setFormData((prev) => ({ ...prev, familyHistory: e.target.value }))}
          rows={3}
        />
      </div>
    </div>
  ), [formData, addArrayItem, updateArrayItem, removeArrayItem])

  const Step5Records = useMemo(() => (
    <div className='space-y-4'>
      <h3 className='text-lg font-semibold mb-4'>السجلات</h3>
      {isEditing && initialData?._id ? (
        <div className='space-y-6'>
          <ClientMedications clientId={initialData._id} />
          <ClientImmunizations clientId={initialData._id} />
          <ClientTestResults clientId={initialData._id} />
        </div>
      ) : (
        <div className='text-center text-gray-500 py-8'>
          <p>يجب حفظ العميل أولاً لعرض السجلات</p>
        </div>
      )}
    </div>
  ), [isEditing, initialData])

  const Step6Measurements = useMemo(() => (
    <div className='space-y-4'>
      <h3 className='text-lg font-semibold mb-4'>القياسات</h3>
      <div className='grid grid-cols-1 md:grid-cols-2 gap-4'>
        <div>
          <Label htmlFor='dateFileOpening'>تاريخ فتح الملف</Label>
          <Input
            id='dateFileOpening'
            type='date'
            value={formData.dateFileOpening}
            onChange={(e) => setFormData((prev) => ({ ...prev, dateFileOpening: e.target.value }))}
          />
        </div>
        <div>
          <Label htmlFor='bmi'>مؤشر كتلة الجسم (BMI)</Label>
          <Input
            id='bmi'
            type='number'
            step='0.1'
            value={formData.bmi}
            onChange={(e) => setFormData((prev) => ({ ...prev, bmi: e.target.value }))}
            placeholder='سيتم حسابه تلقائياً من الوزن والطول'
          />
        </div>
      </div>
      <div className='space-y-2'>
        <Label>نمط الحياة</Label>
        <div className='grid grid-cols-1 md:grid-cols-2 gap-4'>
          <div>
            <Label htmlFor='lifestyleSmoking' className='text-sm text-gray-600'>التدخين</Label>
            <Input
              id='lifestyleSmoking'
              value={formData.lifestyle.smoking || ''}
                    onChange={(e) =>
                      setFormData((prev) => ({
                        ...prev,
                        lifestyle: { ...prev.lifestyle, smoking: e.target.value },
                      }))
                    }
              placeholder='مثال: لا يدخن، يدخن يومياً'
            />
          </div>
          <div>
            <Label htmlFor='lifestyleAlcohol' className='text-sm text-gray-600'>الكحول</Label>
            <Input
              id='lifestyleAlcohol'
              value={formData.lifestyle.alcohol || ''}
                    onChange={(e) =>
                      setFormData((prev) => ({
                        ...prev,
                        lifestyle: { ...prev.lifestyle, alcohol: e.target.value },
                      }))
                    }
              placeholder='مثال: لا يشرب، يشرب أحياناً'
            />
          </div>
          <div>
            <Label htmlFor='lifestylePhysicalActivity' className='text-sm text-gray-600'>النشاط البدني</Label>
            <Input
              id='lifestylePhysicalActivity'
              value={formData.lifestyle.physicalActivity || ''}
                    onChange={(e) =>
                      setFormData((prev) => ({
                        ...prev,
                        lifestyle: { ...prev.lifestyle, physicalActivity: e.target.value },
                      }))
                    }
              placeholder='مثال: نشط، قليل النشاط'
            />
          </div>
          <div>
            <Label htmlFor='lifestyleDiet' className='text-sm text-gray-600'>النظام الغذائي</Label>
            <Input
              id='lifestyleDiet'
              value={formData.lifestyle.diet || ''}
                    onChange={(e) =>
                      setFormData((prev) => ({
                        ...prev,
                        lifestyle: { ...prev.lifestyle, diet: e.target.value },
                      }))
                    }
              placeholder='مثال: نظام غذائي صحي'
            />
          </div>
        </div>
      </div>
      <div className='space-y-2'>
        <Label>القياسات الأساسية</Label>
        <div className='grid grid-cols-1 md:grid-cols-2 gap-4'>
          <div>
            <Label htmlFor='bloodPressure' className='text-sm text-gray-600'>ضغط الدم</Label>
            <Input
              id='bloodPressure'
              value={formData.baselineVitals.bloodPressure || ''}
                    onChange={(e) =>
                      setFormData((prev) => ({
                        ...prev,
                        baselineVitals: { ...prev.baselineVitals, bloodPressure: e.target.value },
                      }))
                    }
              placeholder='مثال: 120/80'
            />
          </div>
          <div>
            <Label htmlFor='bloodSugar' className='text-sm text-gray-600'>السكر في الدم</Label>
            <Input
              id='bloodSugar'
              value={formData.baselineVitals.bloodSugar || ''}
                    onChange={(e) =>
                      setFormData((prev) => ({
                        ...prev,
                        baselineVitals: { ...prev.baselineVitals, bloodSugar: e.target.value },
                      }))
                    }
              placeholder='مثال: 90 mg/dL'
            />
          </div>
          <div>
            <Label htmlFor='weight' className='text-sm text-gray-600'>الوزن (كجم)</Label>
            <Input
              id='weight'
              type='number'
              step='0.1'
              value={formData.baselineVitals.weight || ''}
              onChange={(e) =>
                setFormData((prev) => ({
                  ...prev,
                  baselineVitals: {
                    ...prev.baselineVitals,
                    weight: e.target.value ? parseFloat(e.target.value) : undefined,
                  },
                }))
              }
            />
          </div>
          <div>
            <Label htmlFor='height' className='text-sm text-gray-600'>الطول (سم)</Label>
            <Input
              id='height'
              type='number'
              step='0.1'
              value={formData.baselineVitals.height || ''}
              onChange={(e) =>
                setFormData((prev) => ({
                  ...prev,
                  baselineVitals: {
                    ...prev.baselineVitals,
                    height: e.target.value ? parseFloat(e.target.value) : undefined,
                  },
                }))
              }
            />
          </div>
        </div>
      </div>
    </div>
  ), [formData])

  const Step7Classification = useMemo(() => (
    <div className='space-y-4'>
      <h3 className='text-lg font-semibold mb-4'>التصنيف</h3>
      <div className='grid grid-cols-1 md:grid-cols-2 gap-4'>
        <div>
          <Label htmlFor='clientClassification'>تصنيف العميل</Label>
          <Select
            value={formData.clientClassification}
            onValueChange={(value) =>
              setFormData((prev) => ({
                ...prev,
                clientClassification: value as 'regular' | 'new' | 'chronic' | 'VIP',
              }))
            }
          >
            <SelectTrigger>
              <SelectValue placeholder='اختر التصنيف' />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value='new'>جديد</SelectItem>
              <SelectItem value='regular'>عادي</SelectItem>
              <SelectItem value='chronic'>مزمن</SelectItem>
              <SelectItem value='VIP'>VIP</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>
      <div>
        <Label htmlFor='appointmentAdherence'>التزام العميل بالمواعيد والعلاج</Label>
        <Textarea
          id='appointmentAdherence'
          value={formData.appointmentAdherence}
          onChange={(e) => setFormData((prev) => ({ ...prev, appointmentAdherence: e.target.value }))}
          rows={3}
          placeholder='ملاحظات حول التزام العميل بالمواعيد والعلاج'
        />
      </div>
      <div>
        <Label htmlFor='improvementNotes'>ملاحظات التحسن أو التدهور</Label>
        <Textarea
          id='improvementNotes'
          value={formData.improvementNotes}
          onChange={(e) => setFormData((prev) => ({ ...prev, improvementNotes: e.target.value }))}
          rows={4}
          placeholder='ملاحظات حول حالة العميل وتحسنه أو تدهوره'
        />
      </div>
    </div>
  ), [formData])

  // Render current step
  const renderCurrentStep = () => {
    switch (currentStep) {
      case 1:
        return <div key="step-1">{Step1BasicInfo}</div>
      case 2:
        return <div key="step-2">{Step2Identification}</div>
      case 3:
        return <div key="step-3">{Step3AddressContact}</div>
      case 4:
        return <div key="step-4">{Step4MedicalHistory}</div>
      case 5:
        return <div key="step-5">{Step5Records}</div>
      case 6:
        return <div key="step-6">{Step6Measurements}</div>
      case 7:
        return <div key="step-7">{Step7Classification}</div>
      default:
        return <div key="step-1">{Step1BasicInfo}</div>
    }
  }

  return (
    <>
      <div className='grid grid-cols-1 lg:grid-cols-[60%_40%] gap-6' dir='rtl'>
        {/* Left Column: Form */}
        <div className='space-y-6'>
          <form onSubmit={handleSubmit} className='space-y-6'>
            <ProgressIndicator />
            
            <Card className='shadow-lg border-2'>
              <CardContent className='pt-6'>
                {renderCurrentStep()}
              </CardContent>
            </Card>

            <div className='flex justify-between gap-2 pt-4 border-t bg-white p-4 rounded-lg shadow-md'>
              <Button
                type='button'
                variant='outline'
                onClick={handlePrevious}
                disabled={currentStep === 1}
                className='min-w-[120px]'
              >
                <ChevronRight className='w-4 h-4 ml-1' />
                السابق
              </Button>
              {currentStep < TOTAL_STEPS ? (
                <Button type='button' onClick={handleNext} className='min-w-[120px]'>
                  التالي
                  <ChevronLeft className='w-4 h-4 mr-1' />
                </Button>
              ) : (
                <Button type='button' onClick={handleSaveClick} disabled={isLoading || isSubmitting} className='min-w-[120px]'>
                  {isSubmitting ? 'جاري الحفظ...' : isEditing ? 'تحديث بيانات العميل' : 'حفظ العميل'}
                </Button>
              )}
            </div>
          </form>
        </div>

        {/* Right Column: Live Preview (Sticky) */}
        <div className='lg:sticky lg:top-6 h-fit'>
          <Card className='shadow-xl border-2 bg-gradient-to-br from-blue-50 to-indigo-50'>
            <CardHeader className='bg-gradient-to-r from-blue-600 to-indigo-600 text-white rounded-t-lg'>
              <CardTitle className='text-xl font-bold flex items-center gap-2'>
                <span>معاينة مباشرة</span>
                <span className='text-sm font-normal opacity-90'>({currentStep}/{TOTAL_STEPS})</span>
              </CardTitle>
            </CardHeader>
            <CardContent className='pt-6 max-h-[calc(100vh-200px)] overflow-y-auto'>
              {PreviewSection}
            </CardContent>
          </Card>
        </div>
      </div>

      {/* Confirmation Dialog - Shows after clicking save */}
      <Dialog open={confirmOpen} onOpenChange={setConfirmOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>تأكيد {isEditing ? 'تحديث' : 'إنشاء'} العميل</DialogTitle>
            <DialogDescription>
              هل أنت متأكد أنك تريد {isEditing ? 'تحديث' : 'إنشاء'} هذا العميل؟
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant='outline' type='button' onClick={() => setConfirmOpen(false)}>
              إلغاء
            </Button>
            <Button type='button' onClick={handleConfirm} disabled={isLoading || isSubmitting}>
              {isSubmitting ? 'جاري الحفظ...' : 'تأكيد'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  )
}
